### ISSUE TITLE
EAN13 bar code generator Font Change

### ISSUE THREAD

**Issue by lc62** [smorodsky/ean-barcode-generator#1]
Hi,

I'm using the EAN13 barcpde generator, and I'll need to modify the font type and size for the "human-readable digits", changing the actual OCR-B for an Helvetica 12pt.

Is it possible to do it?

Thanks,
Luca

**Comment by smorodsky** [comment]
Hey, Luke!

Built-in font conforms to the specification. Sorry, unable to change it. However, the script generate a regular object of id. You can manually replace any part.
